### ISSUE TITLE
Delete button doesn't work

### ISSUE THREAD

**Issue by carnager** [Unia/gcolor3#27]
In Saved colors window hitting the delete button has no effect at all.

**Comment by Unia** [comment]
Can you elaborate a bit more on the precise actions you have taken? There are many ways to use the delete button :) In any case, I have not been able to reproduce your issue here.

I have, however, discovered another issue:
  * Saving colors without entering a name for them uses their hex value as key. However, GKeyFile ignores lines starting with `#`. A stupid mistake on my side.

**Comment by carnager** [comment]
too late, it works now with latest git :)
